# Build Stage
FROM golang:1.23-alpine AS builder
WORKDIR /holylibrary

# Copy dependencies first
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the binary
RUN go build -o holylibrary-backend

# Runtime Stage
FROM alpine:latest
WORKDIR /holylibrary

# Copy the binary from the build stage
COPY --from=builder /holylibrary/holylibrary-backend .

# Expose the port
EXPOSE 8080

# Run the binary
CMD ["./holylibrary-backend"]
