# Use the official Go image
FROM golang:1.23-alpine

# Set environment variables
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app

# Copy go files and dependencies
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the binary
RUN go build -o holyLibrary-backend

# Expose the port
EXPOSE 8080

# Run the app
CMD ["./holyLibrary-backend"]